project:
  type: website
  output-dir: docs/

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - gallery.qmd
  search: false
  image: "bmwmini.001.png"  
  open-graph: true  
  
format:
  html:
    fontsize: large
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-expand: 0



